# Generated by Django 5.2.7 on 2025-11-18 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companydriver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company Driver', 'verbose_name_plural': 'Company Drivers'},
        ),
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver Profile', 'verbose_name_plural': 'Driver Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='company',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companydriver',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='companydriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY_OWNER', 'Company Owner'), ('INDIVIDUAL_DRIVER', 'Individual Driver'), ('COMPANY_DRIVER', 'Company Driver')], db_index=True, default='INDIVIDUAL_DRIVER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='companydriver',
            index=models.Index(fields=['company', 'is_active'], name='accounts_co_company_ab17bf_idx'),
        ),
        migrations.AddIndex(
            model_name='companydriver',
            index=models.Index(fields=['driver', 'is_active'], name='accounts_co_driver__fe5eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['verified', 'license_expiry'], name='accounts_dr_verifie_d6acad_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'role'], name='accounts_us_email_e4fb19_idx'),
        ),
    ]
