# Generated by Django 5.2.7 on 2025-11-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_companydriver_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='AdminProfile',
        ),
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Profile', 'verbose_name_plural': 'Admin Profiles'},
        ),
    ]
