# Generated by Django 5.2.7 on 2025-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profile_adminprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
