# Generated by Django 5.2.7 on 2026-01-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAILER TRUCK', 'Trailer Truck'), ('FLATBED TRUCK', 'Flatbed Truck'), ('SPECIAL TRUCK', 'Special Truck'), ('CONTAINER TRUCK', 'Container Truck')], default='TRAILER TRUCK', max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('license_number', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('colour', models.CharField(max_length=255)),
                ('road_worthiness_certificate', models.FileField(upload_to='road_worthiness/')),
                ('vehicle_insurance', models.FileField(upload_to='vehicle_insurances/')),
                ('inspection_report', models.FileField(upload_to='inspection_reports/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
